#Photo Booth Config:
"CAMERA_BUTTON_PIN" : 21 # GPIO pin that is connected to 'take photo' button
"EXIT_BUTTON_PIN"   : 13 # GPIO pin that is connected to 'exit' button (optional)
"TOTAL_PICS"        : 4  # Number of pics to be taken
"PREP_DELAY"        : 4  # Number of seconds as users prepare to have photo taken

#GPIO Debounce Duration
# (This may help avoid "phantom presses" caused by electronic interference)
"DEBOUNCE_TIME"     : 0.05 # Min duration (seconds) button is required to be "pressed in" for.

# Take photos at this resolution:
"PHOTO_W"           : 1920
"PHOTO_H"           : 1152

# Resolution of the photo booth display:
"SCREEN_W"          : 800
"SCREEN_H"          : 480

# Camera setup
"CAMERA_ROTATION"   : 270 # Rotation of the camera
"CAMERA_HFLIP"      : True # When preparing for photos, the preview will be flipped horizontally.

# Folder to save images
"SAVE_RAW_IMAGES_FOLDER" : "photos"

# Test purposes only:
"TESTMODE_AUTOPRESS_BUTTON" : False # Should the button be automatically pressed? (only used for testing)
